/**
 * SchemaNMToken.java
 *
 * This file was generated by MapForce 2007sp1.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */

package com.altova.types;

public class SchemaNMToken extends SchemaToken {
	public SchemaNMToken() {
		super();
	}

	public SchemaNMToken(String newvalue) {
		super(newvalue);
	}

	public SchemaNMToken(SchemaNMToken newvalue) {
		super((SchemaToken)newvalue);
	}
}
