/**
 * SchemaNormalizedString.java
 *
 * This file was generated by MapForce 2007sp1.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */

package com.altova.types;

public class SchemaNormalizedString extends SchemaString {
	public SchemaNormalizedString() {
		super();
	}

	public SchemaNormalizedString(String newvalue) {
		super(newvalue);
	}

	public SchemaNormalizedString(SchemaNormalizedString newvalue) {
		super((SchemaString)newvalue);
	}
}
