/**
 * SchemaLanguage.java
 *
 * This file was generated by MapForce 2007sp1.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */

package com.altova.types;

public class SchemaLanguage extends SchemaToken {
	public SchemaLanguage() {
		super();
	}

	public SchemaLanguage(String newvalue) {
		super(newvalue);
	}

	public SchemaLanguage(SchemaLanguage newvalue) {
		super((SchemaToken)newvalue);
	}
}
