/**
 * SchemaEntity.java
 *
 * This file was generated by MapForce 2007sp1.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */

package com.altova.types;

public class SchemaEntity extends SchemaNCName {
	public SchemaEntity() {
		super();
	}

	public SchemaEntity(String newvalue) {
		super(newvalue);
	}

	public SchemaEntity(SchemaEntity newvalue) {
		super((SchemaNCName)newvalue);
	}
}
