/**
 * SchemaToken.java
 *
 * This file was generated by MapForce 2007sp1.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */

package com.altova.types;

public class SchemaToken extends SchemaNormalizedString {
	public SchemaToken() {
		super();
	}

	public SchemaToken(String newvalue) {
		super(newvalue);
	}

	public SchemaToken(SchemaToken newvalue) {
		super((SchemaNormalizedString)newvalue);
	}
}
