/**
 * SchemaName.java
 *
 * This file was generated by MapForce 2007sp1.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */

package com.altova.types;

public class SchemaName extends SchemaToken {
	public SchemaName() {
		super();
	}

	public SchemaName(String newvalue) {
		super(newvalue);
	}

	public SchemaName(SchemaName newvalue) {
		super((SchemaToken)newvalue);
	}
}
