/**
 * SchemaID.java
 *
 * This file was generated by MapForce 2007sp1.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */

package com.altova.types;

public class SchemaID extends SchemaNCName {
	public SchemaID() {
		super();
	}

	public SchemaID(String newvalue) {
		super(newvalue);
	}

	public SchemaID(SchemaID newvalue) {
		super((SchemaNCName)newvalue);
	}
}
