/**
 * TypesIncompatibleException.java
 *
 * This file was generated by MapForce 2007sp1.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */


package com.altova.types;


public class TypesIncompatibleException extends SchemaTypeException {
  protected SchemaType object1;
  protected SchemaType object2;

  public TypesIncompatibleException(SchemaType newobj1, SchemaType newobj2) {
    super("Incompatible schema-types");
    object1 = newobj1;
    object2 = newobj2;
  }

  public TypesIncompatibleException(Exception other) {
    super(other);
  }
}
