/**
 * TypesNotConvertableException.java
 *
 * This file was generated by MapForce 2007sp1.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */


package com.altova.types;


public class ValuesNotConvertableException extends SchemaTypeException {
  protected SchemaType object1;
  protected SchemaType object2;

  public ValuesNotConvertableException(SchemaType newobj1, SchemaType newobj2) {
    super("Value '" + newobj1.toString() + "' could not be converted to type " + newobj2.getClass().getName());
    object1 = newobj1;
    object2 = newobj2;
  }

  public ValuesNotConvertableException(Exception other) {
    super(other);
  }
}
