/**
 * Db.java
 *
 * This file was generated by MapForce 2007sp1.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */
package com.altova.functions;

import com.altova.types.*;


public class Db {

//  private static Hashtable _s_InstanceIDs = new Hashtable();	// not used at the moment

  // ---------- null-processing functions ----------

  // result = setNull()
  /* Result is a NULLed string
  */
  public static SchemaString setNull() {
	SchemaString sRes = new SchemaString();
	sRes.setNull();
    return sRes;
  }

}