////////////////////////////////////////////////////////////////////////
//
// DataTypeValidatorDate.java
//
// This file was generated by MapForce 2007sp1.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

package com.altova.text.edi;

public class  DataTypeValidatorDate extends DataTypeValidator {

	public DataTypeValidatorDate (int minLength, int maxLength) {
		super (minLength, maxLength);
	}

	public boolean makeValidOnRead (StringBuffer s, Parser.Context context) {
		while (Character.isWhitespace(s.charAt(0)))
			s.deleteCharAt(0);

		if (s.toString().length() == 6 )
			if (Integer.parseInt(s.substring(0, 2)) <= 50)
				s.insert(0, "20");
			else
				s.insert(0, "19");

		s.insert(4, '-');
		s.insert(7, '-');
		return true;
	}

	public boolean makeValidOnWrite (StringBuffer s, Writer writer) {
		int i=0;

		while (i < s.length())
			if (s.charAt(i) == '-')
				s.deleteCharAt(i);
			else
				i++;

		if (getMaxLength() == 6)
			s.delete(0, 2);

		s.setLength(getMinLength());
		return true;
	}
}
