////////////////////////////////////////////////////////////////////////
//
// DataTypeValidator.java
//
// This file was generated by MapForce 2007sp1.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

package com.altova.text.edi;

public abstract class  DataTypeValidator {

	int mMinLength;
	int mMaxLength;

	public int getMinLength() {
		return mMinLength;
	}
	
	public int getMaxLength() {
		return mMaxLength;
	}

	protected DataTypeValidator(int minLength, int maxLength) {
		mMinLength = minLength;
		mMaxLength = maxLength;
	}
	
	public abstract boolean makeValidOnRead (StringBuffer s, Parser.Context context);
	public abstract  boolean makeValidOnWrite (StringBuffer s, Writer writer);
}	
