////////////////////////////////////////////////////////////////////////
//
// EDISettings.java
//
// This file was generated by MapForce 2007sp1.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

package com.altova.text.edi;

public class EDISettings {
	private ServiceChars m_ServiceChars = new ServiceChars();

	private boolean m_TerminateSegmentsWithLinefeed = false;

	private boolean m_AutoCompleteData = true;
		
	private String mVersion = "";
		
	private String mRelease = "";

	public ServiceChars getServiceChars() {
		return m_ServiceChars;
	}

	public boolean getTerminateSegmentsWithLinefeed() {
		return m_TerminateSegmentsWithLinefeed;
	}

	public boolean getAutoCompleteData() {
		return m_AutoCompleteData;
	}

	public void setTerminateSegmentsWithLinefeed(boolean rhs) {
		m_TerminateSegmentsWithLinefeed = rhs;
	}

	public void setAutoCompleteData(boolean rhs) {
		m_AutoCompleteData = rhs;
	}
	
	public void setVersion(String ver) {
		mVersion=ver;
	}
	
	public String getVersion() {
		return mVersion;
	}
	
	public void setRelease(String rel) {
		mRelease = rel;
	}
	
	public String getRelease() {
		return mRelease;
	}
}
